src/config/mputils/changelog.txt
src/scripts/staging/item_and_recipes/03_three/recipes.add.shaped.zs
src/scripts/staging/item_and_recipes/03_three/recipes.remove.zs

Cyclic updated the player launcher recipe to now require a diamond, which doesn't fit age 3. This reverts it back to the old recipe.

Restore Cyclic player launcher recipe

---

src/scripts/crafttweaker/recipes/mods/stevescarts.zs

Make Steve's Carts 2 liquid sensor craftable in age 3 by replacing the diamond with a platinum plate.
Also refactor stevecarts.zs so the recipes are in a logical order.
Fixes #3152

fix(recipe): Replace diamond in liquid sensor with platinum plate

---

src/config/mputils/changelog.txt
src/config/pickletweaks.cfg

Add Cyclic swords and Twilight Forest's glass sword to pickletweak's config so they stop showing "BROKEN" despite not being broken.

fix(pickletweaks): Fix "BROKEN" from wrongly showing on certain swords

---

src/config/mputils/changelog.txt
src/scripts/crafttweaker/recipes/mods/natura.zs

Swap metadata in Bloodwood and Ghostwood plank recipes so they stop crafting each other.
Fixes #3173

fix(natura): Fix Bloodwood and Ghostwood making each others planks

---

src/scripts/crafttweaker/integrations/mods/galacticcraftAndExtraplanets.zs
src/scripts/crafttweaker/integrations/mods/modularMachinery/hydraulicPress.zs
src/scripts/crafttweaker/staging/itemsAndRecipes/mods/extraplanets.zs
src/scripts/crafttweaker/staging/itemsAndRecipes/mods/galacticraft.zs

Remove recipes and JEI presence of compressed zinc from Extra Planets due to it having no purpose or function.
fixes #3168

refactor(extraplanets): Remove compressed zinc

---

src/config/extendedcrafting.cfg

Disable Iridium Singularity in Extended Crafting config due to not having iridium in the pack.
Fixes #2985

fix(extendedcrafting): Disable Iridium Singularity

---

src/config/mputils/changelog.txt
src/scripts/crafttweaker/integrations/mods/betterwithmods.zs

Script Better With Mod's nether coal recipe to make 1 per craft instead of 4.

fix(betterwithmods): Nerf nether coal to make 1 instead of 4

---

src/config/mputils/changelog.txt
src/scripts/crafttweaker/oredict/ores.zs

Stoped removing the Content Tweaker ores from their oredicts so they can be processed by machines other than the quartz grindstone.
Fixes #3147

fix(contenttweaker): Add ores to oredicts to allow processing

---

src/config/abyssalcraft.cfg

the minimum block hardness to resist Lesser Shoggoth acid spit was changed from 3 to 2.1 in AbyssalCraft 1.9.4.9 and this significantly helps with their griefing and some to their currently very high difficulty. Also recommend updating the pack to the latest Abyssalcraft version for the next SevTech release as there are several anti-griefing bug fixes (breaking bedrock, destroying tile entities etc).
relevant abyssalcraft commit: https://github.com/Shinoow/AbyssalCraft/commit/8eabf832ac0cfc4f8fa4901505029e573abc63f1

Changes shoggoth block hardness to match current version

---

src/scripts/crafttweaker/integrations/mods/appliedenergistics2.zs
src/scripts/crafttweaker/recipes/mods/actuallyadditions.zs
src/scripts/crafttweaker/recipes/mods/overloaded.zs
src/scripts/crafttweaker/recipes/mods/stevescarts.zs

Due to addition of JEID, enchantment IDs are no longer shorts, which meant certain items were not craftable.
Particular example - RS Fortune Upgrade inscriber recipe did not recognise enchanted book post update. Removed ID being cast as short wherever it was present to prevent this from coming up elsewhere.

Fix: crafting recipes with enchanted books

---

src/config/mputils/changelog.txt

Prestige and Traverse mentioned twice in changelog with older versions

Remove duplicate mods

---

src/scripts/crafttweaker/staging/itemsAndRecipes/mods/astralsorcery.zs

The infused crystal pickaxe now respects game stages ore hiding, thus it can be enabled.

feat: stage Infused Crystal Pickaxe to Stage 2

---

src/scripts/crafttweaker/integrations/dye.zs

`blockWool` oredict is empty in 3.1.x, whichever mod was populating it no longer does.
Use `wool` oredict instead. This is the only instance of a crafting recipe attempting to use `blockWool`.
Closes #3642

fix: dyed wool crafting recipes

---

src/scripts/crafttweaker/staging/itemsAndRecipes/mods/stevescarts.zs

What does that config option do if not disable the Easter Event?
They're definitely gone now.

refactor: remove Steve's Carts Easter Event Items

---

src/config/mputils/changelog.txt
src/scripts/crafttweaker/integrations/mods/immersive/engineering/metalPress.zs

Adds unpacking recipe for:
* Clay Blocks
* Diamond Blocks
* Lapis Blocks
* Redstone Blocks
* Emerald Blocks
closes #3694

fix: make certain packing recipes reversible using unpacking mold

---

src/config/mputils/changelog.txt
src/config/naturescompass.cfg

fix: add JEID error biome to Nature's Compass blacklist

---

src/config/mputils/changelog.txt
src/scripts/crafttweaker/integrations/dye.zs

AE2 looks in the dyeSilver ore dictionary for Light Gray. This does not exist without script creating it. Note this is also a problem in a "vanilla" AE2 setup - dyeSilver does not exist in this case either.
closes #3683

fix: Light Gray Dye Powder now useable in AE2 Color Applicator

---

src/config/carryon.cfg
src/config/mputils/changelog.txt

fix: Blacklist Chisels and Bits blocks from being picked up by carryon

---

src/config/carryon.cfg

fix: blacklist enderstorage blocks in carryon

---

src/config/car/car.json
src/config/car/fuel_station.json
src/config/car/generator.json

The fuel used in the UltimateCarMod is labelled "bio_diesel". However, the bio diesel enabled in the modpack is IE's "biodiesel". On my personal savefile i changed these values and now the mod works as intended.

UltimateCarMod accepted fuel fix
